apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alloy-credentials
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: alloy-credentials
  dataFrom:
    - extract:
        key: secret/alloy
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
