zitadel:
  masterkeySecretName: zitadel-credentials
  configmapConfig:
    ExternalDomain: iam.nieri0x73.com
    ExternalSecure: true
    ExternalPort: 443
    TLS:
      Enabled: false
    Database:
      Postgres:
        Host: postgres-cluster-rw.databases.svc.cluster.local
        Port: 5432
        Database: zitadel
        MaxOpenConns: 10
        MaxIdleConns: 5
        MaxConnLifetime: 30m
        MaxConnIdleTime: 5m
        User:
          Username: zitadel
          SSL:
            Mode: disable
        Admin:
          Username: postgres
          SSL:
            Mode: disable
    FirstInstance:
      Org:
        Name: nieri0x73
        Human:
          UserName: admin
          FirstName: Admin
          LastName: User
          Email:
            Address: admin@nieri0x73.com
            Verified: true
          PasswordChangeRequired: true
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
env:
  - name: ZITADEL_DATABASE_POSTGRES_USER_PASSWORD
    valueFrom:
      secretKeyRef:
        name: zitadel-credentials
        key: password
  - name: ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD
    valueFrom:
      secretKeyRef:
        name: zitadel-credentials
        key: postgres-password
  - name: ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORD
    valueFrom:
      secretKeyRef:
        name: zitadel-credentials
        key: admin-password
postgresql:
  enabled: false
