apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: actualbudget
  namespace: apps
spec:
  hosts:
    - finance.nieri0x73.com
  gateways:
    - actualbudget
  http:
    - route:
        - destination:
            host: actualbudget
            port:
              number: 5006
