injector:
  enabled: false
server:
  image:
    repository: hashicorp/vault
  standalone:
    enabled: true
    config: |
      ui = true

      listener "tcp" {
        tls_disable = 1
        address = "[::]:8200"
        cluster_address = "[::]:8201"
      }

      storage "file" {
        path = "/vault/data"
      }

      seal "ocikms" {
        key_id              = "ocid1.key.oc1.sa-vinhedo-1.hfu76zpoaaejy.ab3ggljr76f22ft2tgr5xbfxujuhxesdb7ogmn5mjiaoxxx74hr7m2cvf5kq"
        crypto_endpoint     = "https://hfu76zpoaaejy-crypto.kms.sa-vinhedo-1.oci.oraclecloud.com"
        management_endpoint = "https://hfu76zpoaaejy-management.kms.sa-vinhedo-1.oci.oraclecloud.com"
        auth_type_api_key   = false
      }

      telemetry {
        prometheus_retention_time = "30s"
        disable_hostname          = true
      }

      audit {
        type = "file"
        options = {
          file_path = "/vault/data/audit.log"
        }
      }
  logLevel: "warn"
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 256Mi
  dataStorage:
    enabled: true
    size: 2Gi
    storageClass: longhorn
  terminationGracePeriodSeconds: 30
  preStopSleepSeconds: 10
ui:
  enabled: true
