apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: certmanager-credentials
  namespace: cert-manager
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: certmanager-credentials
  dataFrom:
    - extract:
        key: secret/cert-manager
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
