# +argocd:skip-file-rendering
cluster:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:17
  storage:
    size: 5Gi
    storageClass: longhorn
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  bootstrap:
    initdb:
      database: app
      owner: app
      secret:
        name: postgres-credentials # injected via External Secrets
  backup:
    retentionPolicy: "7d"
