server:
  dev:
    enabled: false
  ha:
    enabled: false
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 256Mi
  dataStorage:
    enabled: true
    size: 2Gi
    storageClass: longhorn
ui:
  enabled: true
