# +argocd:skip-file-rendering
server:
  dev:
    enabled: false
  ha:
    enabled: false
  extraConfig: |
    seal "ocikms" {
      key_id              = env("VAULT_SEAL_KEY_ID")
      crypto_endpoint     = env("VAULT_SEAL_CRYPTO_ENDPOINT")
      management_endpoint = env("VAULT_SEAL_MANAGEMENT_ENDPOINT")
      auth_type_api_key   = false
    }
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 256Mi
  dataStorage:
    enabled: true
    size: 2Gi
    storageClass: longhorn
ui:
  enabled: true
