apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: actualbudget
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/nieri0x73/oci-free-k8s
      targetRevision: HEAD
      ref: values
    - repoURL: https://community-charts.github.io/helm-charts
      chart: actualbudget
      targetRevision: 1.9.1
      helm:
        releaseName: actualbudget
        valueFiles:
          - $values/gitops/config/actualbudget/values.yaml
    - repoURL: https://github.com/nieri0x73/oci-free-k8s
      targetRevision: HEAD
      path: gitops/config/actualbudget/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
