apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/nieri0x73/oci-free-k8s
      targetRevision: HEAD
      ref: values
    - repoURL: https://charts.goauthentik.io
      chart: authentik
      targetRevision: 2026.2.3
      helm:
        releaseName: authentik
        valueFiles:
          - $values/gitops/config/authentik/values.yaml
    - repoURL: https://github.com/nieri0x73/oci-free-k8s
      targetRevision: HEAD
      path: gitops/config/authentik/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: security
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
