apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: evolution-api
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/nieri0x73/oci-free-k8s
    targetRevision: HEAD
    path: gitops/config/evolution-api
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
