apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/nieri0x73/oci-free-k8s
      targetRevision: HEAD
      ref: values
    - repoURL: https://charts.external-secrets.io
      chart: external-secrets
      targetRevision: 2.7.0
      helm:
        releaseName: external-secrets
        valueFiles:
          - $values/gitops/config/external-secrets/values.yaml
    - repoURL: https://github.com/nieri0x73/oci-free-k8s
      targetRevision: HEAD
      path: gitops/config/external-secrets/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: security
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
