apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: firefly
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/nieri0x73/oci-free-k8s
      targetRevision: HEAD
      ref: values
    - repoURL: https://firefly-iii.github.io/kubernetes/
      chart: firefly-iii-stack
      targetRevision: 0.10.0
      helm:
        releaseName: finance
        valueFiles:
          - $values/gitops/config/firefly/values.yaml
    - repoURL: https://github.com/nieri0x73/oci-free-k8s
      targetRevision: HEAD
      path: gitops/config/firefly/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
