domain: "https://pass.nieri0x73.com"
signupsAllowed: false
invitationOrgName: "Nieri0x73 Passkey"
adminToken:
  existingSecret: vaultwarden-credentials
  existingSecretKey: ADMIN_TOKEN
image:
  extraVarsSecret: vaultwarden-credentials
storage:
  data:
    name: vaultwarden-data
    size: 1Gi
    accessMode: ReadWriteOnce
resources:
  requests:
    cpu: 25m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 256Mi
