apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: evolution-api-credentials
  namespace: apps
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: evolution-api-credentials
  dataFrom:
    - extract:
        key: secret/evolution-api
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
