apiVersion: apps/v1
kind: Deployment
metadata:
  name: vikunja
  namespace: apps
  labels:
    app: vikunja
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vikunja
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: vikunja
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: vikunja
          image: docker.io/vikunja/vikunja:2.4.0
          ports:
            - containerPort: 3456
              protocol: TCP
          envFrom:
            - secretRef:
                name: vikunja-credentials
          env:
            - name: VIKUNJA_SERVICE_PUBLICURL
              value: "https://planner.nieri0x73.com"
            - name: VIKUNJA_SERVICE_INTERFACE
              value: ":3456"
            - name: VIKUNJA_SERVICE_ENABLEREGISTRATION
              value: "false"
            - name: VIKUNJA_SERVICE_TIMEZONE
              value: "America/Sao_Paulo"
            - name: VIKUNJA_DATABASE_TYPE
              value: "sqlite"
            - name: VIKUNJA_DATABASE_PATH
              value: "/db/vikunja.db"
            - name: VIKUNJA_FILES_BASEPATH
              value: "/files"
          volumeMounts:
            - name: data
              mountPath: /db
            - name: files
              mountPath: /files
          resources:
            requests:
              cpu: 25m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 384Mi
          livenessProbe:
            httpGet:
              path: /api/v1/info
              port: 3456
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /api/v1/info
              port: 3456
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: vikunja-data
        - name: files
          persistentVolumeClaim:
            claimName: vikunja-data
