apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/nieri0x73/oci-free-k8s
      targetRevision: HEAD
      ref: values
    - repoURL: https://guerzon.github.io/vaultwarden
      chart: vaultwarden
      targetRevision: 2.0.1
      helm:
        releaseName: vaultwarden
        valueFiles:
          - $values/gitops/apps/vaultwarden/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: vaultwarden
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
