crds:
  enabled: true
defaultRules:
  create: true
  rules:
    etcd: false
    kubeControllerManager: false
    kubeSchedulerAlerting: false
    kubeSchedulerRecording: false
    kubeProxy: false
alertmanager:
  enabled: false
grafana:
  enabled: true
  admin:
    existingSecret: prometheus-credentials
    userKey: GRAFANA_ADMIN_USER
    passwordKey: GRAFANA_ADMIN_PASSWORD
  defaultDashboardsEnabled: true
  defaultDashboardsTimezone: America/Sao_Paulo
  grafana.ini:
    server:
      root_url: https://monitoring.nieri0x73.com
    security:
      cookie_secure: true
    users:
      allow_sign_up: false
  persistence:
    enabled: true
    type: pvc
    storageClassName: longhorn
    size: 5Gi
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  service:
    type: ClusterIP
    port: 80
  sidecar:
    dashboards:
      enabled: true
      searchNamespace: ALL
    datasources:
      enabled: true
kubernetesServiceMonitors:
  enabled: true
kubeApiServer:
  enabled: true
kubelet:
  enabled: true
  serviceMonitor:
    cAdvisor: true
    probes: true
    resource: true
kubeControllerManager:
  enabled: false
coreDns:
  enabled: true
kubeDns:
  enabled: false
kubeEtcd:
  enabled: false
kubeScheduler:
  enabled: false
kubeProxy:
  enabled: false
kubeStateMetrics:
  enabled: true
kube-state-metrics:
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi
nodeExporter:
  enabled: true
prometheus-node-exporter:
  resources:
    requests:
      cpu: 25m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 64Mi
prometheusOperator:
  enabled: true
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  admissionWebhooks:
    patch:
      resources:
        requests:
          cpu: 10m
          memory: 32Mi
        limits:
          cpu: 100m
          memory: 64Mi
thanosRuler:
  enabled: false
prometheus:
  enabled: true
  prometheusSpec:
    replicas: 1
    shards: 1
    retention: 15d
    retentionSize: 12GB
    externalLabels:
      cluster: oci-free-k8s
    scrapeInterval: 60s
    scrapeTimeout: 10s
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    scrapeConfigSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 15Gi
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1536Mi
