apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: externaldns-credentials
  namespace: networking
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: externaldns-credentials
  dataFrom:
    - extract:
        key: secret/external-dns
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
