apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/nieri0x73/oci-free-k8s
      targetRevision: HEAD
      ref: values
    - repoURL: https://charts.bitnami.com/bitnami
      chart: keycloak
      targetRevision: 25.2.0
      helm:
        releaseName: keycloak
        valueFiles:
          - $values/gitops/apps/keycloak/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: security
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
