image:
  registry: quay.io
  repository: keycloak/keycloak
  tag: 26.3.3
auth:
  adminUser: admin
  existingSecret: keycloak-credentials
  passwordSecretKey: adminPassword
production: true
proxyHeaders: xforwarded
logging:
  level: WARN
postgresql:
  enabled: true
  image:
    tag: latest
  auth:
    existingSecret: keycloak-credentials
    secretKeys:
      userPasswordKey: postgresPassword
resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi
metrics:
  enabled: true
