auth:
  adminUser: admin
  existingSecret: keycloak-credentials
  passwordSecretKey: adminPassword
production: true
proxy: edge
logging:
  level: WARN
postgresql:
  enabled: true
  auth:
    existingSecret: keycloak-credentials
resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi
metrics:
  enabled: true
